conan-build: &conan-build
  name: Build Conan package
  command: |
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    conan install ..
    conan build ..

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs: 
  win: circleci/windows@2.4.0

jobs:
  gcc-7_x64:
    docker:
      - image: conanio/gcc7
    working_directory: ~/daggy/build_gcc-7_x64
    steps:
      - checkout:
          path: ~/daggy
      - run:
          name: Upgrade conan
          command: sudo pip install --upgrade conan
      - run: *conan-build
  msvc2019:
    executor: 
      name: win/default
    working_directory: ~/daggy/build_msvc2019_x64
    steps:
      - checkout:
          path: ~/daggy
      - run:
          name: Install conan
          command: pip install --upgrade conan
      - run: *conan-build
workflows:
  version: 2.1
  build_and_test:
    jobs:
    - gcc-7_x64
    - msvc2019